name: Build

on: [push]

jobs:
  linux:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - name: get-cmake
        uses: lukka/get-cmake@v2.3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: get-pipenv
        run: |
          sudo apt-get install python3-wheel
          python -m pip install --upgrade pip
          pip install pipenv

      - name: setup
        run: python setup.py

      - name: Build docs
        run: |
          cmake --build build --target buildDocs -- -j 4

      - name: Run-tests
        run: cmake --build build --target generateCoverage -- -j 4

      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./build/coverage.xml

          # - name: Deploy 🚀
          #   uses: JamesIves/github-pages-deploy-action@3.4.9
          #   with:
          #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          #     BRANCH: gh-pages # The branch the action should deploy to.
          #     FOLDER: build/docs/web # The folder the action should deploy.


  windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1

      - name: get-cmake
        uses: lukka/get-cmake@v2.3

      - name: get-gcovr
        uses: BSFishy/pip-action@v1
        with:
          packages: gcovr

      - name: get-pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: setup
        run: python setup.py
